### ISSUE TITLE
Moving the cursor based on deltatime rather than a static amount per interval

### ISSUE THREAD

**Issue by Tylemagne** [Tylemagne/Gopher360#20]
@sighol - I haven't ever done this from scratch before, but I know it's a popular solution for things that are intended to run at multiple different framerates. Would it be difficult for Gopher to be configured to run at different framerates (one variable changed) without re-defining the speeds intended for each mode? I have tried looking into framerate-independent speed in the past, but I don't remember ever coming up with a major solution. Or perhaps it's okay to leave it at 144FPS for everyone, even if they may only see 60 since it's the same speed across all platforms anyways?

Also, I always planned for version 1.0 to be run from within a Win32 window (not a console). Would making the switch be difficult using VS2015?

For example, 60FPS, 75FPS, 120FPS, 144FPS, etc.

**Comment by sighol** [comment]
You can change the FPS by changing the `Gopher::FPS` constant in *Gopher.h*. The speed values does not need to be updated after changing the FPS (see the calculation in the `Gopher::getDelta()` method).

Running on my computer, the program uses very little CPU time with 166 FPS (the program mostly sleeps). So unless you are running the program on a really old computer, I don't see the point in adding an option to choose the FPS. 166 FPS feel very smooth to me.

I don't think switching to a GUI application will be more difficult in VS2015 than in older VS versions, but I no experience in making GUI in C++.
