### ISSUE TITLE
Disable gother in games

### ISSUE THREAD

**Issue by mlostekk** [Tylemagne/Gopher360#28]
Hello,

is it somehow possible to disable gother in games? This "double" controlling (with gamepad & simulated mouse) leads to issues while playing (i.e. Wither3)

**Comment by sighol** [comment]
I think you can press the start and back buttons at the same time to toggle
Gopher

**Comment by avi201085** [comment]
tenx a lot very help
 100% work with presinng start and back buttons at the same time//for me
