### ISSUE TITLE
Still can't find config.ini

### ISSUE THREAD

**Issue by shadwalker9** [Tylemagne/Gopher360#42]
Even after downloading the zip from the latest release it seems to be missing, and in the master it mentions it being for .986. 
Is there anyway I can just make the config.ini?

**Comment by kie8** [comment]
Download this version and you will have it.
 https://github.com/wishIwasabear/Gopher360/releases/tag/v0.986

**Comment by ChrisKillerKeller** [comment]
I have the same problem, I do have the config file and can start it without problems, but when I add gopher and the config file to the autostart folder, gopher will display this error of not finding the config file alothough it is right there in the same folder.

Any solutions?
