### ISSUE TITLE
Please Add a Donate Button

### ISSUE THREAD

**Issue by develogix** [Tylemagne/Gopher360#67]
I've been using this as I broke my right wrist and it is amazing. I'd love to throw the devs some beer money or something!

**Comment by Tylemagne** [comment]
Thanks! I'm glad it helped you out. Let's see if I can get this right... If this works, I'll add it to the main page.

[![Donate](https://img.shields.io/badge/Donate-PayPal-green.svg)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=ETDWNUEJG2UY2)

**Comment by develogix** [comment]
Done! Thanks a bunch!
